### ISSUE TITLE
Does this work with ARGB/RGB colour codes

### ISSUE THREAD

**Issue by Wagnerp** [nokola/InlineColorPicker#1]
Hi

I was wondering if this work with ARGB/RGB colour codes inside of `cs` files?

**Comment by nokola** [comment]
Yes it does!

**Comment by nokola** [comment]
No - it should work in .cs files. Maybe we are discussing a different use case than I imagined. Do you mind providing more info? expected/actual behavior, screenshot, etc?

**Comment by Wagnerp** [comment]
I don't think the VISX package is working properly

![image](https://user-images.githubusercontent.com/949607/128301087-0c611341-acb2-4d14-a301-1f0bfca3334c.png)

```txt
05/08/2021 07:19:39 AM - Microsoft VSIX Installer
05/08/2021 07:19:39 AM - -------------------------------------------
05/08/2021 07:19:39 AM - vsixinstaller.exe version:
05/08/2021 07:19:39 AM - 17.0.2145-preview2
05/08/2021 07:19:39 AM - -------------------------------------------
05/08/2021 07:19:39 AM - Command line parameters:
05/08/2021 07:19:39 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Peter William Wagner\Desktop\InlineColorPicker.vsix
05/08/2021 07:19:39 AM - -------------------------------------------
05/08/2021 07:19:39 AM - Microsoft VSIX Installer
05/08/2021 07:19:39 AM - -------------------------------------------
05/08/2021 07:19:39 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (14ad81e1) since it does not support extensions
05/08/2021 07:19:39 AM - Skipping product Microsoft.VisualStudio.Product.BuildTools (d9dde3fb) since it does not support extensions
05/08/2021 07:19:39 AM - Initializing Install...
05/08/2021 07:19:39 AM - Extension Details...
05/08/2021 07:19:39 AM - 	Identifier         : InlineColorPicker.Microsoft.5b11f3ae-dd7e-422e-84bc-5cec46f80687
05/08/2021 07:19:39 AM - 	Name               : Inline Color Picker
05/08/2021 07:19:39 AM - 	Author             : Nokola
05/08/2021 07:19:39 AM - 	Version            : 2.3
05/08/2021 07:19:39 AM - 	Description        : Color picker extension for Visual Studio.
05/08/2021 07:19:39 AM - 	Locale             : en-US
05/08/2021 07:19:39 AM - 	MoreInfoURL        : 
05/08/2021 07:19:39 AM - 	InstalledByMSI     : False
05/08/2021 07:19:39 AM - 	SupportedFrameworkVersionRange : [4.5,)
05/08/2021 07:19:39 AM - 
05/08/2021 07:19:39 AM - 	SignatureState     : Unsigned
05/08/2021 07:19:39 AM - 	Supported Products : 
05/08/2021 07:19:39 AM - 		Microsoft.VisualStudio.Community
05/08/2021 07:19:39 AM - 			Version : [11.0,18.0)
05/08/2021 07:19:39 AM - 			ProductArchitecture : notSpecified
05/08/2021 07:19:39 AM - 		Microsoft.VisualStudio.Pro
05/08/2021 07:19:39 AM - 			Version : [11.0,18.0)
05/08/2021 07:19:39 AM - 			ProductArchitecture : notSpecified
05/08/2021 07:19:39 AM - 		Microsoft.VisualStudio.Enterprise
05/08/2021 07:19:39 AM - 			Version : [11.0,18.0)
05/08/2021 07:19:39 AM - 			ProductArchitecture : notSpecified
05/08/2021 07:19:39 AM - 
05/08/2021 07:19:39 AM - 	References         : 
05/08/2021 07:19:39 AM - 	Prerequisites      : 
05/08/2021 07:19:39 AM - 		-------------------------------------------------------
05/08/2021 07:19:39 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
05/08/2021 07:19:39 AM - 		Name         : Visual Studio core editor
05/08/2021 07:19:39 AM - 		Version      : [11.0,18.0)
05/08/2021 07:19:39 AM - 
05/08/2021 07:19:39 AM - Signature Details...
05/08/2021 07:19:39 AM - 	Extension is not signed.
05/08/2021 07:19:39 AM - 
05/08/2021 07:19:39 AM - Searching for applicable products...
05/08/2021 07:19:39 AM - Found installed product - Global Location
05/08/2021 07:19:39 AM - Found installed product - Visual Studio Community 2019 Preview
05/08/2021 07:19:39 AM - Found installed product - Visual Studio Community 2019 (2)
05/08/2021 07:19:39 AM - Found installed product - Visual Studio Community 2022 Preview
05/08/2021 07:19:39 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

**Comment by nokola** [comment]
Thanks! I'm not sure why this happens - do you mind opening a new issue with the exact steps that lead to the error below?
Unfortunately I don't have much time to update this extension, that's why I released the code in the open.

btw, you can also install the extension from here: https://marketplace.visualstudio.com/items?itemName=NikolaMSFT.InlineColorPicker
and for VS 2022: https://marketplace.visualstudio.com/items?itemName=NikolaMSFT.InlineColorPickerX64Preview

**Comment by Wagnerp** [comment]
> Thanks! I'm not sure why this happens - do you mind opening a new issue with the exact steps that lead to the error below?
> Unfortunately I don't have much time to update this extension, that's why I released the code in the open.
> 
> btw, you can also install the extension from here: https://marketplace.visualstudio.com/items?itemName=NikolaMSFT.InlineColorPicker
> and for VS 2022: https://marketplace.visualstudio.com/items?itemName=NikolaMSFT.InlineColorPickerX64Preview

@nokola I'll check it out later :)

**Comment by Wagnerp** [comment]
Hi @nokola 

The VSIX did work under a clean install of VS, however since then I've started to use ReSharper that has a similar feature.

**Comment by nokola** [comment]
Nice, thanks for the info!
